name: Secret Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays
  workflow_dispatch:  # Allow manual triggering

jobs:
  scanning:
    name: TruffleHog Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for better secret detection

      - name: TruffleHog scan
        uses: trufflesecurity/trufflehog@v3.88.18
        with:
          extra_args: "--only-verified"
