name: Secret Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays
  workflow_dispatch:  # Allow manual triggering

jobs:
  scanning:
    name: TruffleHog Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      issues: write  # Needed for creating issues on failure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for better secret detection

      - name: TruffleHog scan
        uses: trufflesecurity/trufflehog-actions-scan@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🚨 Potential Secrets Detected',
              body: 'TruffleHog has detected potential secrets in the codebase. Please review the workflow logs immediately and rotate any exposed credentials.',
              labels: ['security']
            })
